// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: meet/meet.proto

package meet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To          string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Carrier     string `protobuf:"bytes,3,opt,name=carrier,proto3" json:"carrier,omitempty"`
	SfuServerId string `protobuf:"bytes,4,opt,name=sfuServerId,proto3" json:"sfuServerId,omitempty"`
}

func (x *InboundCallRequest) Reset() {
	*x = InboundCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meet_meet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InboundCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundCallRequest) ProtoMessage() {}

func (x *InboundCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meet_meet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundCallRequest.ProtoReflect.Descriptor instead.
func (*InboundCallRequest) Descriptor() ([]byte, []int) {
	return file_meet_meet_proto_rawDescGZIP(), []int{0}
}

func (x *InboundCallRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *InboundCallRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InboundCallRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *InboundCallRequest) GetSfuServerId() string {
	if x != nil {
		return x.SfuServerId
	}
	return ""
}

type MeetId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MeetId) Reset() {
	*x = MeetId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meet_meet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeetId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetId) ProtoMessage() {}

func (x *MeetId) ProtoReflect() protoreflect.Message {
	mi := &file_meet_meet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetId.ProtoReflect.Descriptor instead.
func (*MeetId) Descriptor() ([]byte, []int) {
	return file_meet_meet_proto_rawDescGZIP(), []int{1}
}

func (x *MeetId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OutboundCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetId  string `protobuf:"bytes,1,opt,name=meetId,proto3" json:"meetId,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Carrier string `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
}

func (x *OutboundCallRequest) Reset() {
	*x = OutboundCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meet_meet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboundCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundCallRequest) ProtoMessage() {}

func (x *OutboundCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meet_meet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundCallRequest.ProtoReflect.Descriptor instead.
func (*OutboundCallRequest) Descriptor() ([]byte, []int) {
	return file_meet_meet_proto_rawDescGZIP(), []int{2}
}

func (x *OutboundCallRequest) GetMeetId() string {
	if x != nil {
		return x.MeetId
	}
	return ""
}

func (x *OutboundCallRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *OutboundCallRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *OutboundCallRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

var File_meet_meet_proto protoreflect.FileDescriptor

var file_meet_meet_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x65, 0x74, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x65, 0x65, 0x74, 0x22, 0x74, 0x0a, 0x12, 0x49, 0x6e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x66, 0x75, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x66, 0x75, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1e, 0x0a,
	0x06, 0x4d, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6b, 0x0a,
	0x13, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x32, 0x95, 0x01, 0x0a, 0x0b, 0x4d,
	0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x4d,
	0x65, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x6d, 0x65, 0x65, 0x74, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x2e, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x00, 0x42, 0x3d, 0x0a, 0x14, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x65,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meet_meet_proto_rawDescOnce sync.Once
	file_meet_meet_proto_rawDescData = file_meet_meet_proto_rawDesc
)

func file_meet_meet_proto_rawDescGZIP() []byte {
	file_meet_meet_proto_rawDescOnce.Do(func() {
		file_meet_meet_proto_rawDescData = protoimpl.X.CompressGZIP(file_meet_meet_proto_rawDescData)
	})
	return file_meet_meet_proto_rawDescData
}

var file_meet_meet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meet_meet_proto_goTypes = []interface{}{
	(*InboundCallRequest)(nil),  // 0: meet.InboundCallRequest
	(*MeetId)(nil),              // 1: meet.MeetId
	(*OutboundCallRequest)(nil), // 2: meet.OutboundCallRequest
}
var file_meet_meet_proto_depIdxs = []int32{
	0, // 0: meet.MeetService.CreateInboundCallMeet:input_type -> meet.InboundCallRequest
	2, // 1: meet.MeetService.CreateOutboundCallMeet:input_type -> meet.OutboundCallRequest
	1, // 2: meet.MeetService.CreateInboundCallMeet:output_type -> meet.MeetId
	1, // 3: meet.MeetService.CreateOutboundCallMeet:output_type -> meet.MeetId
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meet_meet_proto_init() }
func file_meet_meet_proto_init() {
	if File_meet_meet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meet_meet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InboundCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meet_meet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeetId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meet_meet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutboundCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meet_meet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meet_meet_proto_goTypes,
		DependencyIndexes: file_meet_meet_proto_depIdxs,
		MessageInfos:      file_meet_meet_proto_msgTypes,
	}.Build()
	File_meet_meet_proto = out.File
	file_meet_meet_proto_rawDesc = nil
	file_meet_meet_proto_goTypes = nil
	file_meet_meet_proto_depIdxs = nil
}
