// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: meet/meet.proto

package meet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeetServiceClient is the client API for MeetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeetServiceClient interface {
	// dw -> sfu
	CreateOutboundMeet(ctx context.Context, in *OutboundMeetRequest, opts ...grpc.CallOption) (*BareResponse, error)
	CreatePrivateMeet(ctx context.Context, in *PrivateMeetRequest, opts ...grpc.CallOption) (*BareResponse, error)
	HangUpMeetByManager(ctx context.Context, in *HangUpMeetByManagerRequest, opts ...grpc.CallOption) (*BareResponse, error)
	JoinMeetByManager(ctx context.Context, in *JoinMeetByManagerRequest, opts ...grpc.CallOption) (*BareResponse, error)
	TerminateMeet(ctx context.Context, in *TerminateMeetRequest, opts ...grpc.CallOption) (*BareResponse, error)
	// sfu -> dw
	CreateInboundMeet(ctx context.Context, in *InboundMeetRequest, opts ...grpc.CallOption) (*InboundMeetResponse, error)
	CreateMeetRecord(ctx context.Context, in *CreateMeetRecordRequest, opts ...grpc.CallOption) (*BareResponse, error)
	GetGreeting(ctx context.Context, in *GetGreetingRequest, opts ...grpc.CallOption) (*GetGreetingResponse, error)
	JoinMeetByUser(ctx context.Context, in *JoinMeetByUserRequest, opts ...grpc.CallOption) (*BareResponse, error)
	HangUpMeetByUser(ctx context.Context, in *HangUpMeetByUserRequest, opts ...grpc.CallOption) (*BareResponse, error)
}

type meetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetServiceClient(cc grpc.ClientConnInterface) MeetServiceClient {
	return &meetServiceClient{cc}
}

func (c *meetServiceClient) CreateOutboundMeet(ctx context.Context, in *OutboundMeetRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/CreateOutboundMeet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) CreatePrivateMeet(ctx context.Context, in *PrivateMeetRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/CreatePrivateMeet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) HangUpMeetByManager(ctx context.Context, in *HangUpMeetByManagerRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/HangUpMeetByManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) JoinMeetByManager(ctx context.Context, in *JoinMeetByManagerRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/JoinMeetByManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) TerminateMeet(ctx context.Context, in *TerminateMeetRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/TerminateMeet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) CreateInboundMeet(ctx context.Context, in *InboundMeetRequest, opts ...grpc.CallOption) (*InboundMeetResponse, error) {
	out := new(InboundMeetResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/CreateInboundMeet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) CreateMeetRecord(ctx context.Context, in *CreateMeetRecordRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/CreateMeetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) GetGreeting(ctx context.Context, in *GetGreetingRequest, opts ...grpc.CallOption) (*GetGreetingResponse, error) {
	out := new(GetGreetingResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/GetGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) JoinMeetByUser(ctx context.Context, in *JoinMeetByUserRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/JoinMeetByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetServiceClient) HangUpMeetByUser(ctx context.Context, in *HangUpMeetByUserRequest, opts ...grpc.CallOption) (*BareResponse, error) {
	out := new(BareResponse)
	err := c.cc.Invoke(ctx, "/meet.MeetService/HangUpMeetByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetServiceServer is the server API for MeetService service.
// All implementations must embed UnimplementedMeetServiceServer
// for forward compatibility
type MeetServiceServer interface {
	// dw -> sfu
	CreateOutboundMeet(context.Context, *OutboundMeetRequest) (*BareResponse, error)
	CreatePrivateMeet(context.Context, *PrivateMeetRequest) (*BareResponse, error)
	HangUpMeetByManager(context.Context, *HangUpMeetByManagerRequest) (*BareResponse, error)
	JoinMeetByManager(context.Context, *JoinMeetByManagerRequest) (*BareResponse, error)
	TerminateMeet(context.Context, *TerminateMeetRequest) (*BareResponse, error)
	// sfu -> dw
	CreateInboundMeet(context.Context, *InboundMeetRequest) (*InboundMeetResponse, error)
	CreateMeetRecord(context.Context, *CreateMeetRecordRequest) (*BareResponse, error)
	GetGreeting(context.Context, *GetGreetingRequest) (*GetGreetingResponse, error)
	JoinMeetByUser(context.Context, *JoinMeetByUserRequest) (*BareResponse, error)
	HangUpMeetByUser(context.Context, *HangUpMeetByUserRequest) (*BareResponse, error)
	mustEmbedUnimplementedMeetServiceServer()
}

// UnimplementedMeetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeetServiceServer struct {
}

func (UnimplementedMeetServiceServer) CreateOutboundMeet(context.Context, *OutboundMeetRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOutboundMeet not implemented")
}
func (UnimplementedMeetServiceServer) CreatePrivateMeet(context.Context, *PrivateMeetRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivateMeet not implemented")
}
func (UnimplementedMeetServiceServer) HangUpMeetByManager(context.Context, *HangUpMeetByManagerRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangUpMeetByManager not implemented")
}
func (UnimplementedMeetServiceServer) JoinMeetByManager(context.Context, *JoinMeetByManagerRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMeetByManager not implemented")
}
func (UnimplementedMeetServiceServer) TerminateMeet(context.Context, *TerminateMeetRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateMeet not implemented")
}
func (UnimplementedMeetServiceServer) CreateInboundMeet(context.Context, *InboundMeetRequest) (*InboundMeetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInboundMeet not implemented")
}
func (UnimplementedMeetServiceServer) CreateMeetRecord(context.Context, *CreateMeetRecordRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeetRecord not implemented")
}
func (UnimplementedMeetServiceServer) GetGreeting(context.Context, *GetGreetingRequest) (*GetGreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGreeting not implemented")
}
func (UnimplementedMeetServiceServer) JoinMeetByUser(context.Context, *JoinMeetByUserRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMeetByUser not implemented")
}
func (UnimplementedMeetServiceServer) HangUpMeetByUser(context.Context, *HangUpMeetByUserRequest) (*BareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangUpMeetByUser not implemented")
}
func (UnimplementedMeetServiceServer) mustEmbedUnimplementedMeetServiceServer() {}

// UnsafeMeetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetServiceServer will
// result in compilation errors.
type UnsafeMeetServiceServer interface {
	mustEmbedUnimplementedMeetServiceServer()
}

func RegisterMeetServiceServer(s grpc.ServiceRegistrar, srv MeetServiceServer) {
	s.RegisterService(&MeetService_ServiceDesc, srv)
}

func _MeetService_CreateOutboundMeet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboundMeetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).CreateOutboundMeet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/CreateOutboundMeet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).CreateOutboundMeet(ctx, req.(*OutboundMeetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_CreatePrivateMeet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateMeetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).CreatePrivateMeet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/CreatePrivateMeet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).CreatePrivateMeet(ctx, req.(*PrivateMeetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_HangUpMeetByManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangUpMeetByManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).HangUpMeetByManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/HangUpMeetByManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).HangUpMeetByManager(ctx, req.(*HangUpMeetByManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_JoinMeetByManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMeetByManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).JoinMeetByManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/JoinMeetByManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).JoinMeetByManager(ctx, req.(*JoinMeetByManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_TerminateMeet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateMeetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).TerminateMeet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/TerminateMeet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).TerminateMeet(ctx, req.(*TerminateMeetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_CreateInboundMeet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundMeetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).CreateInboundMeet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/CreateInboundMeet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).CreateInboundMeet(ctx, req.(*InboundMeetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_CreateMeetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).CreateMeetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/CreateMeetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).CreateMeetRecord(ctx, req.(*CreateMeetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_GetGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).GetGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/GetGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).GetGreeting(ctx, req.(*GetGreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_JoinMeetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMeetByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).JoinMeetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/JoinMeetByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).JoinMeetByUser(ctx, req.(*JoinMeetByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetService_HangUpMeetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangUpMeetByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetServiceServer).HangUpMeetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meet.MeetService/HangUpMeetByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetServiceServer).HangUpMeetByUser(ctx, req.(*HangUpMeetByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetService_ServiceDesc is the grpc.ServiceDesc for MeetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meet.MeetService",
	HandlerType: (*MeetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOutboundMeet",
			Handler:    _MeetService_CreateOutboundMeet_Handler,
		},
		{
			MethodName: "CreatePrivateMeet",
			Handler:    _MeetService_CreatePrivateMeet_Handler,
		},
		{
			MethodName: "HangUpMeetByManager",
			Handler:    _MeetService_HangUpMeetByManager_Handler,
		},
		{
			MethodName: "JoinMeetByManager",
			Handler:    _MeetService_JoinMeetByManager_Handler,
		},
		{
			MethodName: "TerminateMeet",
			Handler:    _MeetService_TerminateMeet_Handler,
		},
		{
			MethodName: "CreateInboundMeet",
			Handler:    _MeetService_CreateInboundMeet_Handler,
		},
		{
			MethodName: "CreateMeetRecord",
			Handler:    _MeetService_CreateMeetRecord_Handler,
		},
		{
			MethodName: "GetGreeting",
			Handler:    _MeetService_GetGreeting_Handler,
		},
		{
			MethodName: "JoinMeetByUser",
			Handler:    _MeetService_JoinMeetByUser_Handler,
		},
		{
			MethodName: "HangUpMeetByUser",
			Handler:    _MeetService_HangUpMeetByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meet/meet.proto",
}
