// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/task.proto

package io.channel.api.proto;

public interface TaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.TaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.task.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.task.Task task = 1;</code>
   * @return The task.
   */
  io.channel.api.proto.Task getTask();
  /**
   * <code>.task.Task task = 1;</code>
   */
  io.channel.api.proto.TaskOrBuilder getTaskOrBuilder();
}
