// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/task.proto

package io.channel.api.proto;

public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string shard_name = 2;</code>
   * @return The shardName.
   */
  java.lang.String getShardName();
  /**
   * <code>string shard_name = 2;</code>
   * @return The bytes for shardName.
   */
  com.google.protobuf.ByteString
      getShardNameBytes();

  /**
   * <code>string run_key = 3;</code>
   * @return The runKey.
   */
  java.lang.String getRunKey();
  /**
   * <code>string run_key = 3;</code>
   * @return The bytes for runKey.
   */
  com.google.protobuf.ByteString
      getRunKeyBytes();

  /**
   * <code>.task.QueueName queue_name = 4;</code>
   * @return The enum numeric value on the wire for queueName.
   */
  int getQueueNameValue();
  /**
   * <code>.task.QueueName queue_name = 4;</code>
   * @return The queueName.
   */
  io.channel.api.proto.QueueName getQueueName();

  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
