// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/task.proto

package io.channel.api.proto;

public interface UpdateTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.UpdateTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.task.QueueName queue_name = 1;</code>
   * @return The enum numeric value on the wire for queueName.
   */
  int getQueueNameValue();
  /**
   * <code>.task.QueueName queue_name = 1;</code>
   * @return The queueName.
   */
  io.channel.api.proto.QueueName getQueueName();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.google.protobuf.Duration data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Duration data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.Duration getData();
  /**
   * <code>.google.protobuf.Duration data = 3;</code>
   */
  com.google.protobuf.DurationOrBuilder getDataOrBuilder();
}
