// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/task.proto

package io.channel.api.proto;

public final class TaskOuterClass {
  private TaskOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_TaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_TaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_ShowTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_ShowTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_SubmitTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_SubmitTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_UpdateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_UpdateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_DeleteTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_DeleteTaskRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017task/task.proto\022\004task\032\036google/protobuf" +
      "/duration.proto\"j\n\004Task\022\n\n\002id\030\001 \001(\t\022\022\n\ns" +
      "hard_name\030\002 \001(\t\022\017\n\007run_key\030\003 \001(\t\022#\n\nqueu" +
      "e_name\030\004 \001(\0162\017.task.QueueName\022\014\n\004data\030\005 " +
      "\001(\t\"(\n\014TaskResponse\022\030\n\004task\030\001 \001(\0132\n.task" +
      ".Task\"B\n\017ShowTaskRequest\022#\n\nqueue_name\030\001" +
      " \001(\0162\017.task.QueueName\022\n\n\002id\030\002 \001(\t\"U\n\021Sub" +
      "mitTaskRequest\022#\n\nqueue_name\030\001 \001(\0162\017.tas" +
      "k.QueueName\022\014\n\004data\030\002 \001(\t\022\r\n\005delay\030\003 \001(\t" +
      "\"m\n\021UpdateTaskRequest\022#\n\nqueue_name\030\001 \001(" +
      "\0162\017.task.QueueName\022\n\n\002id\030\002 \001(\t\022\'\n\004data\030\003" +
      " \001(\0132\031.google.protobuf.Duration\"D\n\021Delet" +
      "eTaskRequest\022#\n\nqueue_name\030\001 \001(\0162\017.task." +
      "QueueName\022\n\n\002id\030\002 \001(\t*\177\n\tQueueName\022\023\n\017AU" +
      "TOMATION_RULE\020\000\022\r\n\tMARKETING\020\001\022\010\n\004MEET\020\002" +
      "\022\020\n\014MEET_SESSION\020\003\022\014\n\010POST_LOG\020\004\022\010\n\004USER" +
      "\020\005\022\r\n\tUSER_CHAT\020\006\022\013\n\007MANAGER\020\0072\356\001\n\020TaskQ" +
      "ueueService\0221\n\004show\022\025.task.ShowTaskReque" +
      "st\032\022.task.TaskResponse\0225\n\006submit\022\027.task." +
      "SubmitTaskRequest\032\022.task.TaskResponse\0229\n" +
      "\nupdateTask\022\027.task.UpdateTaskRequest\032\022.t" +
      "ask.TaskResponse\0225\n\006delete\022\027.task.Delete" +
      "TaskRequest\032\022.task.TaskResponseB\030\n\024io.ch" +
      "annel.api.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_task_Task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_task_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_Task_descriptor,
        new java.lang.String[] { "Id", "ShardName", "RunKey", "QueueName", "Data", });
    internal_static_task_TaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_task_TaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_TaskResponse_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_task_ShowTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_task_ShowTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_ShowTaskRequest_descriptor,
        new java.lang.String[] { "QueueName", "Id", });
    internal_static_task_SubmitTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_task_SubmitTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_SubmitTaskRequest_descriptor,
        new java.lang.String[] { "QueueName", "Data", "Delay", });
    internal_static_task_UpdateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_task_UpdateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_UpdateTaskRequest_descriptor,
        new java.lang.String[] { "QueueName", "Id", "Data", });
    internal_static_task_DeleteTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_task_DeleteTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_DeleteTaskRequest_descriptor,
        new java.lang.String[] { "QueueName", "Id", });
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
