stage: development
auth:
  authGeneralUrl: test
  authAdminURL: test
  jwtServiceKey: ${JWT_SERVICE_KEY}
port:
  admin: 3000
  desk: 3001
  front: 3002
  general: 3003
psql:
  schema: public
  dbname: app_store
  host: localhost
  port: 5432
  user: app_store
  password: abc
  sslmode: disable



