stage: development
auth:
  authGeneralUrl: https://appstore-api.eks.exp.channel.io
  authAdminURL: https://appstore-admin.eks.exp.channel.io
  jwtServiceKey: test
port: 3020
psql:
  schema: public
  dbname: app_store
  host: localhost
  port: 5432
  user: app_store
  password: abc
  sslmode: disable
sentry:
  dsn: ''
  tracesSampleRate: 0
