stage: development
auth:
  authGeneralUrl: test
  authAdminURL: test
  jwtServiceKey: test
port: 3000
psql:
  schema: public
  dbname: app_store
  host: localhost
  port: 5432
  user: app_store
  password: abc
  sslmode: disable
sentry:
  dsn: ''
  tracesSampleRate: 0
