stage: exp
serviceName: app-store-api.exp.channel.io
channelServiceName: api.exp.channel.io
systemLogTableName: exp_app_system_logs
auth:
  authGeneralUrl: https://api.exp.channel.io
  authAdminURL: https://admin-api.in.exp.channel.io
  jwtServiceKey: ${JWT_SERVICE_KEY}
port: ${PORT}
psql:
  schema: public
  dbname: app_store_exp
  host: db.exp.channel.io
  port: 5432
  user: app_store
  password: ${PSQL_PASSWORD}
  sslmode: require
  maxOpenConn: 50
log:
  console:
    level: debug
  sentry:
    level: error
    dsn: https://94086f3f685212aaeed799d618411501@o104101.ingest.sentry.io/4506738076418048
    tracesSampleRate: 1.0
rateLimiter:
  url: https://rate-limiter.in.exp.channel.io
  appRuleId: 12
  managerRuleId: 11
  userRuleId: 13
services:
  CHANNEL-ADMIN-API: "admin-api.in.exp.channel.io"
  CHANNEL-API: "api.exp.channel.io"
  DOCUMENT-API: "document-api.exp.channel.io"
  APP-STORE-API: "app-store-api.exp.channel.io"
