stage: exp
auth:
  authGeneralUrl: https://appstore-api.eks.exp.channel.io
  authAdminURL: https://appstore-admin.eks.exp.channel.io
  jwtServiceKey: ${JWT_SERVICE_KEY}
port: 3000
psql:
  schema: public
  dbname: app_store
  host: db.exp.channel.io
  port: 5432
  user: app_store
  sslmode: disable
