stage: production
auth:
  authAdminURL: https://admin-api.in.channel.io
  jwtServiceKey: ${JWT_SERVICE_KEY}
port: 3020
psql:
  schema: public
  dbname: app_store
  host: psql.in.channel.io
  port: 5432
  password: ${PSQL_PASSWORD}
  user: app_store
  sslmode: disable
log:
  console:
    level: debug
  sentry:
    level: error
    dsn: https://b2a067b7a7320aa60be1f44b5cb36623@o104101.ingest.sentry.io/4506738092539904
    tracesSampleRate: 1.0
