stage: production
port: 3020
psql:
  schema: public
  dbname: app_store
  host: psql.in.channel.io
  port: 5432
  user: app_store
  sslmode: disable
sentry:
  dsn: https://b2a067b7a7320aa60be1f44b5cb36623@o104101.ingest.sentry.io/4506738092539904
  tracesSampleRate: 1.0
