// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface CloseMeetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.CloseMeetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meet_id = 1;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meet_id = 1;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();

  /**
   * <code>.meet.CloseMeetCode code = 2;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.meet.CloseMeetCode code = 2;</code>
   * @return The code.
   */
  io.channel.api.proto.CloseMeetCode getCode();

  /**
   * <code>optional .meet.GuideVoice guide_voice = 3;</code>
   * @return Whether the guideVoice field is set.
   */
  boolean hasGuideVoice();
  /**
   * <code>optional .meet.GuideVoice guide_voice = 3;</code>
   * @return The guideVoice.
   */
  io.channel.api.proto.GuideVoice getGuideVoice();
  /**
   * <code>optional .meet.GuideVoice guide_voice = 3;</code>
   */
  io.channel.api.proto.GuideVoiceOrBuilder getGuideVoiceOrBuilder();
}
