// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface GetGreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.GetGreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string guide_voice_url = 1;</code>
   * @return The guideVoiceUrl.
   */
  java.lang.String getGuideVoiceUrl();
  /**
   * <code>string guide_voice_url = 1;</code>
   * @return The bytes for guideVoiceUrl.
   */
  com.google.protobuf.ByteString
      getGuideVoiceUrlBytes();
}
