// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface InitializeInboundMeetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.InitializeInboundMeetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_meet_available = 1;</code>
   * @return The isMeetAvailable.
   */
  boolean getIsMeetAvailable();

  /**
   * <code>string guide_voice_url = 2;</code>
   * @return The guideVoiceUrl.
   */
  java.lang.String getGuideVoiceUrl();
  /**
   * <code>string guide_voice_url = 2;</code>
   * @return The bytes for guideVoiceUrl.
   */
  com.google.protobuf.ByteString
      getGuideVoiceUrlBytes();

  /**
   * <code>string meet_id = 3;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meet_id = 3;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();
}
