// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public final class Meet {
  private Meet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_AudioFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_AudioFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_Peer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_Peer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_BareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_BareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InboundMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InboundMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_HangUpMeetByManagerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_HangUpMeetByManagerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InitializeInboundMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InitializeInboundMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_CreateMeetRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_CreateMeetRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_OutboundMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_OutboundMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InboundMeetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InboundMeetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_PrivateMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_PrivateMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByManagerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByManagerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_TerminateMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_TerminateMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_HangUpMeetByUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_HangUpMeetByUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InitializeInboundMeetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InitializeInboundMeetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_RejectMeetByUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_RejectMeetByUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017meet/meet.proto\022\004meet\"l\n\tAudioFile\022\016\n\006" +
      "bucket\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022" +
      "\024\n\014content_type\030\004 \001(\t\022\020\n\010duration\030\005 \001(\001\022" +
      "\014\n\004size\030\006 \001(\003\"\"\n\006Person\022\014\n\004type\030\001 \001(\t\022\n\n" +
      "\002id\030\002 \001(\t\"7\n\004Peer\022\034\n\006person\030\001 \001(\0132\014.meet" +
      ".Person\022\021\n\tdevice_id\030\002 \001(\t\"9\n\014BareRespon" +
      "se\022)\n\rresponse_code\030\001 \001(\0162\022.meet.Respons" +
      "eCode\"z\n\022InboundMeetRequest\022\014\n\004from\030\001 \001(" +
      "\t\022\n\n\002to\030\002 \001(\t\022\017\n\007carrier\030\003 \001(\t\022\025\n\rsfu_se" +
      "rver_id\030\004 \001(\t\022\021\n\tdevice_id\030\005 \001(\t\022\017\n\007meet" +
      "_id\030\006 \001(\t\"B\n\025JoinMeetByUserRequest\022\030\n\004pe" +
      "er\030\001 \001(\0132\n.meet.Peer\022\017\n\007meet_id\030\002 \001(\t\"G\n" +
      "\032HangUpMeetByManagerRequest\022\030\n\004peer\030\001 \001(" +
      "\0132\n.meet.Peer\022\017\n\007meet_id\030\002 \001(\t\"8\n\034Initia" +
      "lizeInboundMeetRequest\022\n\n\002to\030\001 \001(\t\022\014\n\004fr" +
      "om\030\002 \001(\t\"P\n\027CreateMeetRecordRequest\022\017\n\007m" +
      "eet_id\030\001 \001(\t\022$\n\013meet_record\030\002 \001(\0132\017.meet" +
      ".AudioFile\"\300\001\n\023OutboundMeetRequest\022\017\n\007me" +
      "et_id\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\017\n" +
      "\007carrier\030\004 \001(\t\022\032\n\004user\030\005 \001(\0132\014.meet.Pers" +
      "on\022\033\n\007manager\030\006 \001(\0132\n.meet.Peer\022\027\n\017guide" +
      "_voice_url\030\007 \001(\t\022\033\n\023p_asserted_identity\030" +
      "\010 \001(\t\"k\n\023InboundMeetResponse\022)\n\rresponse" +
      "_code\030\001 \001(\0162\022.meet.ResponseCode\022\017\n\007meet_" +
      "id\030\002 \001(\t\022\030\n\004peer\030\003 \001(\0132\n.meet.Peer\"B\n\022Pr" +
      "ivateMeetRequest\022\017\n\007meet_id\030\001 \001(\t\022\033\n\007man" +
      "ager\030\002 \001(\0132\n.meet.Peer\"E\n\030JoinMeetByMana" +
      "gerRequest\022\030\n\004peer\030\001 \001(\0132\n.meet.Peer\022\017\n\007" +
      "meet_id\030\002 \001(\t\"]\n\026JoinMeetByUserResponse\022" +
      ")\n\rresponse_code\030\001 \001(\0162\022.meet.ResponseCo" +
      "de\022\030\n\004peer\030\002 \001(\0132\n.meet.Peer\"m\n\024Terminat" +
      "eMeetRequest\022\017\n\007meet_id\030\001 \001(\t\022\022\n\nchannel" +
      "_id\030\002 \001(\t\022\034\n\017guide_voice_url\030\003 \001(\tH\000\210\001\001B" +
      "\022\n\020_guide_voice_url\"D\n\027HangUpMeetByUserR" +
      "equest\022\030\n\004peer\030\001 \001(\0132\n.meet.Peer\022\017\n\007meet" +
      "_id\030\002 \001(\t\"d\n\035InitializeInboundMeetRespon" +
      "se\022\031\n\021is_meet_available\030\001 \001(\010\022\027\n\017guide_v" +
      "oice_url\030\002 \001(\t\022\017\n\007meet_id\030\003 \001(\t\"H\n\027Rejec" +
      "tMeetByUserRequest\022\034\n\006person\030\001 \001(\0132\014.mee" +
      "t.Person\022\017\n\007meet_id\030\002 \001(\t*i\n\014ResponseCod" +
      "e\022\013\n\007SUCCESS\020\000\022\017\n\013BAD_REQUEST\020\001\022\020\n\014UNAUT" +
      "HORIZED\020\002\022\r\n\tFORBIDDEN\020\003\022\r\n\tNOT_FOUND\020\004\022" +
      "\013\n\007UNKNOWN\020\0052\260\006\n\013MeetService\022C\n\022CreateOu" +
      "tboundMeet\022\031.meet.OutboundMeetRequest\032\022." +
      "meet.BareResponse\022A\n\021CreatePrivateMeet\022\030" +
      ".meet.PrivateMeetRequest\032\022.meet.BareResp" +
      "onse\022K\n\023HangUpMeetByManager\022 .meet.HangU" +
      "pMeetByManagerRequest\032\022.meet.BareRespons" +
      "e\022G\n\021JoinMeetByManager\022\036.meet.JoinMeetBy" +
      "ManagerRequest\032\022.meet.BareResponse\022?\n\rTe" +
      "rminateMeet\022\032.meet.TerminateMeetRequest\032" +
      "\022.meet.BareResponse\022H\n\021CreateInboundMeet" +
      "\022\030.meet.InboundMeetRequest\032\031.meet.Inboun" +
      "dMeetResponse\022E\n\020CreateMeetRecord\022\035.meet" +
      ".CreateMeetRecordRequest\032\022.meet.BareResp" +
      "onse\022`\n\025InitializeInboundMeet\022\".meet.Ini" +
      "tializeInboundMeetRequest\032#.meet.Initial" +
      "izeInboundMeetResponse\022A\n\016JoinMeetByUser" +
      "\022\033.meet.JoinMeetByUserRequest\032\022.meet.Bar" +
      "eResponse\022E\n\020HangUpMeetByUser\022\035.meet.Han" +
      "gUpMeetByUserRequest\032\022.meet.BareResponse" +
      "\022E\n\020RejectMeetByUser\022\035.meet.RejectMeetBy" +
      "UserRequest\032\022.meet.BareResponseB=\n\024io.ch" +
      "annel.api.protoP\001Z#github.com/channel-io" +
      "/ch-proto/meetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meet_AudioFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meet_AudioFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_AudioFile_descriptor,
        new java.lang.String[] { "Bucket", "Key", "Name", "ContentType", "Duration", "Size", });
    internal_static_meet_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meet_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_Person_descriptor,
        new java.lang.String[] { "Type", "Id", });
    internal_static_meet_Peer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meet_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_Peer_descriptor,
        new java.lang.String[] { "Person", "DeviceId", });
    internal_static_meet_BareResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meet_BareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_BareResponse_descriptor,
        new java.lang.String[] { "ResponseCode", });
    internal_static_meet_InboundMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meet_InboundMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InboundMeetRequest_descriptor,
        new java.lang.String[] { "From", "To", "Carrier", "SfuServerId", "DeviceId", "MeetId", });
    internal_static_meet_JoinMeetByUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meet_JoinMeetByUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByUserRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_HangUpMeetByManagerRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meet_HangUpMeetByManagerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_HangUpMeetByManagerRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_InitializeInboundMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meet_InitializeInboundMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InitializeInboundMeetRequest_descriptor,
        new java.lang.String[] { "To", "From", });
    internal_static_meet_CreateMeetRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meet_CreateMeetRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_CreateMeetRecordRequest_descriptor,
        new java.lang.String[] { "MeetId", "MeetRecord", });
    internal_static_meet_OutboundMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meet_OutboundMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_OutboundMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "From", "To", "Carrier", "User", "Manager", "GuideVoiceUrl", "PAssertedIdentity", });
    internal_static_meet_InboundMeetResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_meet_InboundMeetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InboundMeetResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "MeetId", "Peer", });
    internal_static_meet_PrivateMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_meet_PrivateMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_PrivateMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "Manager", });
    internal_static_meet_JoinMeetByManagerRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_meet_JoinMeetByManagerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByManagerRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_JoinMeetByUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_meet_JoinMeetByUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByUserResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "Peer", });
    internal_static_meet_TerminateMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_meet_TerminateMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_TerminateMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "ChannelId", "GuideVoiceUrl", "GuideVoiceUrl", });
    internal_static_meet_HangUpMeetByUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_meet_HangUpMeetByUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_HangUpMeetByUserRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_InitializeInboundMeetResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_meet_InitializeInboundMeetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InitializeInboundMeetResponse_descriptor,
        new java.lang.String[] { "IsMeetAvailable", "GuideVoiceUrl", "MeetId", });
    internal_static_meet_RejectMeetByUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_meet_RejectMeetByUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_RejectMeetByUserRequest_descriptor,
        new java.lang.String[] { "Person", "MeetId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
