// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public final class Meet {
  private Meet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_GuideVoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_GuideVoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_Peer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_Peer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_BareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_BareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InboundMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InboundMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_HangUpMeetByManagerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_HangUpMeetByManagerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_OutboundMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_OutboundMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_InboundMeetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_InboundMeetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_PrivateMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_PrivateMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByManagerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByManagerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_JoinMeetByUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_JoinMeetByUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_TerminateMeetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_TerminateMeetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meet_HangUpMeetByUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meet_HangUpMeetByUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017meet/meet.proto\022\004meet\")\n\nGuideVoice\022\016\n" +
      "\006bucket\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\"\"\n\006Person\022\014\n\004" +
      "type\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"7\n\004Peer\022\034\n\006person" +
      "\030\001 \001(\0132\014.meet.Person\022\021\n\tdevice_id\030\002 \001(\t\"" +
      "9\n\014BareResponse\022)\n\rresponse_code\030\001 \001(\0162\022" +
      ".meet.ResponseCode\"i\n\022InboundMeetRequest" +
      "\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007carrier\030\003 " +
      "\001(\t\022\025\n\rsfu_server_id\030\004 \001(\t\022\021\n\tdevice_id\030" +
      "\005 \001(\t\"B\n\025JoinMeetByUserRequest\022\030\n\004peer\030\001" +
      " \001(\0132\n.meet.Peer\022\017\n\007meet_id\030\002 \001(\t\"G\n\032Han" +
      "gUpMeetByManagerRequest\022\030\n\004peer\030\001 \001(\0132\n." +
      "meet.Peer\022\017\n\007meet_id\030\002 \001(\t\"\212\001\n\023OutboundM" +
      "eetRequest\022\017\n\007meet_id\030\001 \001(\t\022\014\n\004from\030\002 \001(" +
      "\t\022\n\n\002to\030\003 \001(\t\022\017\n\007carrier\030\004 \001(\t\022\032\n\004user\030\005" +
      " \001(\0132\014.meet.Person\022\033\n\007manager\030\006 \001(\0132\n.me" +
      "et.Peer\"\222\001\n\023InboundMeetResponse\022)\n\rrespo" +
      "nse_code\030\001 \001(\0162\022.meet.ResponseCode\022\017\n\007me" +
      "et_id\030\002 \001(\t\022\030\n\004peer\030\003 \001(\0132\n.meet.Peer\022%\n" +
      "\013guide_voice\030\004 \001(\0132\020.meet.GuideVoice\"B\n\022" +
      "PrivateMeetRequest\022\017\n\007meet_id\030\001 \001(\t\022\033\n\007m" +
      "anager\030\002 \001(\0132\n.meet.Peer\"E\n\030JoinMeetByMa" +
      "nagerRequest\022\030\n\004peer\030\001 \001(\0132\n.meet.Peer\022\017" +
      "\n\007meet_id\030\002 \001(\t\"]\n\026JoinMeetByUserRespons" +
      "e\022)\n\rresponse_code\030\001 \001(\0162\022.meet.Response" +
      "Code\022\030\n\004peer\030\002 \001(\0132\n.meet.Peer\"\206\001\n\024Termi" +
      "nateMeetRequest\022\017\n\007meet_id\030\001 \001(\t\022!\n\004code" +
      "\030\002 \001(\0162\023.meet.CloseMeetCode\022*\n\013guide_voi" +
      "ce\030\003 \001(\0132\020.meet.GuideVoiceH\000\210\001\001B\016\n\014_guid" +
      "e_voice\"D\n\027HangUpMeetByUserRequest\022\030\n\004pe" +
      "er\030\001 \001(\0132\n.meet.Peer\022\017\n\007meet_id\030\002 \001(\t*?\n" +
      "\rCloseMeetCode\022\014\n\010COMPLETE\020\000\022\024\n\020NOT_IN_O" +
      "PERATION\020\001\022\n\n\006MISSED\020\002*X\n\014ResponseCode\022\013" +
      "\n\007SUCCESS\020\000\022\020\n\014UNAUTHORIZED\020\001\022\r\n\tFORBIDD" +
      "EN\020\002\022\r\n\tNOT_FOUND\020\003\022\013\n\007UNKNOWN\020\0042\300\004\n\013Mee" +
      "tService\022C\n\022CreateOutboundMeet\022\031.meet.Ou" +
      "tboundMeetRequest\032\022.meet.BareResponse\022A\n" +
      "\021CreatePrivateMeet\022\030.meet.PrivateMeetReq" +
      "uest\032\022.meet.BareResponse\022K\n\023HangUpMeetBy" +
      "Manager\022 .meet.HangUpMeetByManagerReques" +
      "t\032\022.meet.BareResponse\022G\n\021JoinMeetByManag" +
      "er\022\036.meet.JoinMeetByManagerRequest\032\022.mee" +
      "t.BareResponse\022?\n\rTerminateMeet\022\032.meet.T" +
      "erminateMeetRequest\032\022.meet.BareResponse\022" +
      "H\n\021CreateInboundMeet\022\030.meet.InboundMeetR" +
      "equest\032\031.meet.InboundMeetResponse\022A\n\016Joi" +
      "nMeetByUser\022\033.meet.JoinMeetByUserRequest" +
      "\032\022.meet.BareResponse\022E\n\020HangUpMeetByUser" +
      "\022\035.meet.HangUpMeetByUserRequest\032\022.meet.B" +
      "areResponseB=\n\024io.channel.api.protoP\001Z#g" +
      "ithub.com/channel-io/ch-proto/meetb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meet_GuideVoice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meet_GuideVoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_GuideVoice_descriptor,
        new java.lang.String[] { "Bucket", "Key", });
    internal_static_meet_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meet_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_Person_descriptor,
        new java.lang.String[] { "Type", "Id", });
    internal_static_meet_Peer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meet_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_Peer_descriptor,
        new java.lang.String[] { "Person", "DeviceId", });
    internal_static_meet_BareResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meet_BareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_BareResponse_descriptor,
        new java.lang.String[] { "ResponseCode", });
    internal_static_meet_InboundMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meet_InboundMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InboundMeetRequest_descriptor,
        new java.lang.String[] { "From", "To", "Carrier", "SfuServerId", "DeviceId", });
    internal_static_meet_JoinMeetByUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meet_JoinMeetByUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByUserRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_HangUpMeetByManagerRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meet_HangUpMeetByManagerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_HangUpMeetByManagerRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_OutboundMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meet_OutboundMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_OutboundMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "From", "To", "Carrier", "User", "Manager", });
    internal_static_meet_InboundMeetResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meet_InboundMeetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_InboundMeetResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "MeetId", "Peer", "GuideVoice", });
    internal_static_meet_PrivateMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meet_PrivateMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_PrivateMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "Manager", });
    internal_static_meet_JoinMeetByManagerRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_meet_JoinMeetByManagerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByManagerRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
    internal_static_meet_JoinMeetByUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_meet_JoinMeetByUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_JoinMeetByUserResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "Peer", });
    internal_static_meet_TerminateMeetRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_meet_TerminateMeetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_TerminateMeetRequest_descriptor,
        new java.lang.String[] { "MeetId", "Code", "GuideVoice", "GuideVoice", });
    internal_static_meet_HangUpMeetByUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_meet_HangUpMeetByUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meet_HangUpMeetByUserRequest_descriptor,
        new java.lang.String[] { "Peer", "MeetId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
