// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface OutboundMeetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.OutboundMeetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meet_id = 1;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meet_id = 1;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();

  /**
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 3;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>string to = 3;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string carrier = 4;</code>
   * @return The carrier.
   */
  java.lang.String getCarrier();
  /**
   * <code>string carrier = 4;</code>
   * @return The bytes for carrier.
   */
  com.google.protobuf.ByteString
      getCarrierBytes();

  /**
   * <code>.meet.Person user = 5;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.meet.Person user = 5;</code>
   * @return The user.
   */
  io.channel.api.proto.Person getUser();
  /**
   * <code>.meet.Person user = 5;</code>
   */
  io.channel.api.proto.PersonOrBuilder getUserOrBuilder();

  /**
   * <code>.meet.Peer manager = 6;</code>
   * @return Whether the manager field is set.
   */
  boolean hasManager();
  /**
   * <code>.meet.Peer manager = 6;</code>
   * @return The manager.
   */
  io.channel.api.proto.Peer getManager();
  /**
   * <code>.meet.Peer manager = 6;</code>
   */
  io.channel.api.proto.PeerOrBuilder getManagerOrBuilder();

  /**
   * <code>string guide_voice_url = 7;</code>
   * @return The guideVoiceUrl.
   */
  java.lang.String getGuideVoiceUrl();
  /**
   * <code>string guide_voice_url = 7;</code>
   * @return The bytes for guideVoiceUrl.
   */
  com.google.protobuf.ByteString
      getGuideVoiceUrlBytes();
}
