// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface OutboundCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.OutboundCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meetId = 1;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meetId = 1;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();

  /**
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 3;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>string to = 3;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string carrier = 4;</code>
   * @return The carrier.
   */
  java.lang.String getCarrier();
  /**
   * <code>string carrier = 4;</code>
   * @return The bytes for carrier.
   */
  com.google.protobuf.ByteString
      getCarrierBytes();
}
