// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface PrivateMeetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.PrivateMeetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meet_id = 1;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meet_id = 1;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();

  /**
   * <code>.meet.Peer manager = 2;</code>
   * @return Whether the manager field is set.
   */
  boolean hasManager();
  /**
   * <code>.meet.Peer manager = 2;</code>
   * @return The manager.
   */
  io.channel.api.proto.Peer getManager();
  /**
   * <code>.meet.Peer manager = 2;</code>
   */
  io.channel.api.proto.PeerOrBuilder getManagerOrBuilder();
}
