// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface TerminateMeetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.TerminateMeetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meet_id = 1;</code>
   * @return The meetId.
   */
  java.lang.String getMeetId();
  /**
   * <code>string meet_id = 1;</code>
   * @return The bytes for meetId.
   */
  com.google.protobuf.ByteString
      getMeetIdBytes();

  /**
   * <code>.meet.CloseMeetCode code = 2;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.meet.CloseMeetCode code = 2;</code>
   * @return The code.
   */
  io.channel.api.proto.CloseMeetCode getCode();

  /**
   * <code>optional string guide_voice_url = 3;</code>
   * @return Whether the guideVoiceUrl field is set.
   */
  boolean hasGuideVoiceUrl();
  /**
   * <code>optional string guide_voice_url = 3;</code>
   * @return The guideVoiceUrl.
   */
  java.lang.String getGuideVoiceUrl();
  /**
   * <code>optional string guide_voice_url = 3;</code>
   * @return The bytes for guideVoiceUrl.
   */
  com.google.protobuf.ByteString
      getGuideVoiceUrlBytes();
}
