CREATE TABLE APP_ACCOUNTS
(
    account_id CHARACTER VARYING NOT NULL,
    app_id     CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY (account_id, app_id)
);
