// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package call

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CallClient is the client API for Call service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallClient interface {
	// Sip router, ion-sfu, dw(장기적인 관점에선 grpc, as-i -> rest API)
	CreateMeet(ctx context.Context, in *PhoneRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	GetAoRInfo(ctx context.Context, in *AoRRequest, opts ...grpc.CallOption) (*AoRResponse, error)
}

type callClient struct {
	cc grpc.ClientConnInterface
}

func NewCallClient(cc grpc.ClientConnInterface) CallClient {
	return &callClient{cc}
}

func (c *callClient) CreateMeet(ctx context.Context, in *PhoneRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, "/call.Call/CreateMeet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callClient) GetAoRInfo(ctx context.Context, in *AoRRequest, opts ...grpc.CallOption) (*AoRResponse, error) {
	out := new(AoRResponse)
	err := c.cc.Invoke(ctx, "/call.Call/GetAoRInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServer is the server API for Call service.
// All implementations must embed UnimplementedCallServer
// for forward compatibility
type CallServer interface {
	// Sip router, ion-sfu, dw(장기적인 관점에선 grpc, as-i -> rest API)
	CreateMeet(context.Context, *PhoneRequest) (*SessionInfo, error)
	GetAoRInfo(context.Context, *AoRRequest) (*AoRResponse, error)
	mustEmbedUnimplementedCallServer()
}

// UnimplementedCallServer must be embedded to have forward compatible implementations.
type UnimplementedCallServer struct {
}

func (UnimplementedCallServer) CreateMeet(context.Context, *PhoneRequest) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeet not implemented")
}
func (UnimplementedCallServer) GetAoRInfo(context.Context, *AoRRequest) (*AoRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAoRInfo not implemented")
}
func (UnimplementedCallServer) mustEmbedUnimplementedCallServer() {}

// UnsafeCallServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServer will
// result in compilation errors.
type UnsafeCallServer interface {
	mustEmbedUnimplementedCallServer()
}

func RegisterCallServer(s grpc.ServiceRegistrar, srv CallServer) {
	s.RegisterService(&Call_ServiceDesc, srv)
}

func _Call_CreateMeet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServer).CreateMeet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/call.Call/CreateMeet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServer).CreateMeet(ctx, req.(*PhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Call_GetAoRInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AoRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServer).GetAoRInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/call.Call/GetAoRInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServer).GetAoRInfo(ctx, req.(*AoRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Call_ServiceDesc is the grpc.ServiceDesc for Call service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Call_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "call.Call",
	HandlerType: (*CallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeet",
			Handler:    _Call_CreateMeet_Handler,
		},
		{
			MethodName: "GetAoRInfo",
			Handler:    _Call_GetAoRInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "call/call.proto",
}
