name: Build and push image

on:
  pull_request:
  push:
    branches:
      - exp
      - main
      - feature/**
    tags: ["**"]

permissions:
  id-token: write
  contents: read

jobs:
  test_and_compile:
    runs-on: channel-runner-arm64
    container: public.ecr.aws/i8a4b9p4/circleci-base/go:1.21-bullseye-flyway-tools
    env:
      STAGE: ci
      PSQL_HOST: postgres
      PSQL_DBNAME: app_store_ci
      PSQL_USER: app_store
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: app_store
          POSTGRES_DB: app_store_ci
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: channel-io/ch-github-actions/setup-go@v1

      - name: Install tools
        run: make init

      - name: Flyway & make models
        run: |
          make generate

      - name: Run test
        run: |
          MODE=test make test

      - name: build
        run: |
          make build TARGET_OS=linux TARGET_ARCH=arm64

      - name: Upload artifact
        id: upload-artifact
        uses: channel-io/ch-github-actions/artifact-upload@v1
        with:
          source: target

  build-and-push-image:
    if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/')
    runs-on: channel-runner
    needs: test_and_compile
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: channel-io/ch-github-actions/artifact-download@v1
        with:
          repository: ${{ github.event.repository.name }}
          name: ${{ needs.test_and_compile.outputs.artifact-name }}
      - name: Build and push image
        id: build
        uses: channel-io/ch-github-actions/docker-build-push@main

  build-and-push-migration-image:
    if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/')
    runs-on: channel-runner
    needs: test_and_compile
    steps:
      - uses: actions/checkout@v4
      - name: Build and push migration image
        id: build
        uses: channel-io/ch-github-actions/docker-build-push@v1
        with:
          dockerfile: ./deploy/Dockerfile.migration
          suffix: migration
          platforms: linux/amd64,linux/arm64
