// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface AudioFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.AudioFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucket = 1;</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>string bucket = 1;</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string content_type = 4;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string content_type = 4;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>double duration = 5;</code>
   * @return The duration.
   */
  double getDuration();

  /**
   * <code>int64 size = 6;</code>
   * @return The size.
   */
  long getSize();
}
