// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet/meet.proto

package io.channel.api.proto;

public interface JoinMeetByUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meet.JoinMeetByUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meet.ResponseCode response_code = 1;</code>
   * @return The enum numeric value on the wire for responseCode.
   */
  int getResponseCodeValue();
  /**
   * <code>.meet.ResponseCode response_code = 1;</code>
   * @return The responseCode.
   */
  io.channel.api.proto.ResponseCode getResponseCode();

  /**
   * <code>.meet.Peer peer = 2;</code>
   * @return Whether the peer field is set.
   */
  boolean hasPeer();
  /**
   * <code>.meet.Peer peer = 2;</code>
   * @return The peer.
   */
  io.channel.api.proto.Peer getPeer();
  /**
   * <code>.meet.Peer peer = 2;</code>
   */
  io.channel.api.proto.PeerOrBuilder getPeerOrBuilder();
}
